core/urls.py
from django.urls import path
from django.views.generic import TemplateView

from . import auth_views
from .views import (
    ACNotificationView,
    AgentAddView,
    CloturerView,
    ContactDeleteView,
    DocumentDeleteView,
    DocumentUpdateView,
    DocumentUploadView,
    EvenementOuvrirView,
    FinDeSuiviHandlingView,
    MessageCreateView,
    MessageDetailsView,
    MessageUpdateView,
    PublishAndACNotificationView,
    PublishView,
    RevisionsListView,
    SoftDeleteView,
    StructureAddView,
    sirene_api,
)

urlpatterns = [
    path(
        "document-upload/",
        DocumentUploadView.as_view(),
        name="document-upload",
    ),
    path(
        "document-delete/<int:pk>/",
        DocumentDeleteView.as_view(),
        name="document-delete",
    ),
    path(
        "document-update/<int:pk>/",
        DocumentUpdateView.as_view(),
        name="document-update",
    ),
    path(
        "login",
        auth_views.LoginView.as_view(),
        name="login",
    ),
    path(
        "logout",
        auth_views.logout,
        name="logout",
    ),
    path(
        "contacts/suppression/",
        ContactDeleteView.as_view(),
        name="contact-delete",
    ),
    path(
        "message-add/<int:obj_type_pk>/<int:obj_pk>/",
        MessageCreateView.as_view(),
        name="message-add",
    ),
    path(
        "message/<int:pk>/update/",
        MessageUpdateView.as_view(),
        name="message-update",
    ),
    path(
        "suppression/",
        SoftDeleteView.as_view(),
        name="soft-delete",
    ),
    path(
        "publication/",
        PublishView.as_view(),
        name="publish",
    ),
    path(
        "publier-notifier-ac/",
        PublishAndACNotificationView.as_view(),
        name="publish-and-ac-notification",
    ),
    path(
        "notify-ac/",
        ACNotificationView.as_view(),
        name="notify-ac",
    ),
    path(
        "structures/ajout",
        StructureAddView.as_view(),
        name="structure-add",
    ),
    path(
        "agents/ajout",
        AgentAddView.as_view(),
        name="agent-add",
    ),
    path(
        "cloturer/<int:pk>",
        CloturerView.as_view(),
        name="cloturer",
    ),
    path(
        "evenement/<int:pk>/ouvrir/",
        EvenementOuvrirView.as_view(),
        name="evenement-ouvrir",
    ),
    path(
        "evenement/fin-de-suivi/",
        FinDeSuiviHandlingView.as_view(),
        name="evenement-fin-de-suivi",
    ),
    path(
        "siret/<str:siret>/",
        sirene_api,
        name="siret-api",
    ),
    path(
        "revisions/<int:content_type>/<int:pk>/",
        RevisionsListView.as_view(),
        name="revision-list",
    ),
    path(
        "message/<int:pk>/",
        MessageDetailsView.as_view(),
        name="message-view",
    ),
    path(
        "mentions-legales/",
        TemplateView.as_view(template_name="mentions-legales.html"),
        name="mentions-legales",
    ),
    path(
        "politique-de-confidentialite/",
        TemplateView.as_view(template_name="politique-de-confidentialite.html"),
        name="politique-de-confidentialite",
    ),
]

seves/urls.py
from django.conf import settings
from django.urls import include, path
from django.views.generic.base import RedirectView
from mozilla_django_oidc.urls import OIDCCallbackClass

urlpatterns = [
    path("", RedirectView.as_view(pattern_name="sv:evenement-liste"), name="index"),
    path("login-eap-callback", OIDCCallbackClass.as_view(), name="custom_oidc_authentication_callback"),
    path("sv/", include("sv.urls", namespace="sv")),
    path("ssa/", include("ssa.urls", namespace="ssa")),
    path("tiac/", include("tiac.urls", namespace="tiac")),
    path("core/", include("core.urls"), name="core"),
    path("account/", include("account.urls"), name="account"),
    path("oidc/", include("mozilla_django_oidc.urls")),
]

if settings.ADMIN_ENABLED:
    from django.contrib import admin

    admin.site.site_header = "Administration de Sèves"
    admin.site.site_title = "Sèves"
    admin.site.index_title = "Bienvenue sur l'administration de Sèves"
    urlpatterns += [
        path(f"{settings.ADMIN_URL}/", admin.site.urls),
    ]

if settings.DEBUG and settings.ENVIRONMENT != "test":
    urlpatterns.append(path("__debug__/", include("debug_toolbar.urls")))

sv/urls.py
from django.urls import path

from .api_views import search_espece_echantillon
from .views import (
    EvenementDetailView,
    EvenementListView,
    EvenementUpdateView,
    EvenementVisibiliteUpdateView,
    FicheDetectionCreateView,
    FicheDetectionExportView,
    FicheDetectionUpdateView,
    FicheZoneDelimiteeCreateView,
    FicheZoneDelimiteeDeleteView,
    FicheZoneDelimiteeUpdateView,
    VisibiliteStructureView,
)

app_name = "sv"
urlpatterns = [
    path(
        "evenements/",
        EvenementListView.as_view(),
        name="evenement-liste",
    ),
    path(
        "evenement/<str:numero>/",
        EvenementDetailView.as_view(),
        name="evenement-details",
    ),
    path(
        "evenement/<int:pk>/modification/",
        EvenementUpdateView.as_view(),
        name="evenement-update",
    ),
    path(
        "fiches-detection/creation/",
        FicheDetectionCreateView.as_view(),
        name="fiche-detection-creation",
    ),
    path(
        "fiches-detection/export/",
        FicheDetectionExportView.as_view(),
        name="fiche-detection-export",
    ),
    path(
        "fiches-detection/<int:pk>/modification/",
        FicheDetectionUpdateView.as_view(),
        name="fiche-detection-modification",
    ),
    path(
        "evenement/<int:pk>/visibilite/",
        EvenementVisibiliteUpdateView.as_view(),
        name="evenement-visibilite-update",
    ),
    path(
        "api/espece/recherche/",
        search_espece_echantillon,
        name="api-search-espece",
    ),
    path(
        "fiche-zone-delimitee/creation/",
        FicheZoneDelimiteeCreateView.as_view(),
        name="fiche-zone-delimitee-creation",
    ),
    path(
        "fiche-zone-delimitee/<int:pk>/modification/",
        FicheZoneDelimiteeUpdateView.as_view(),
        name="fiche-zone-delimitee-update",
    ),
    path(
        "evenement/<int:pk>/structures/ajout/visibilite",
        VisibiliteStructureView.as_view(),
        name="structure-add-visibilite",
    ),
    path(
        "fiche-zone-delimitee/<int:pk>/delete/",
        FicheZoneDelimiteeDeleteView.as_view(),
        name="fiche-zone-delimitee-delete",
    ),
]

core/models.py
from collections import defaultdict

from django.apps import apps
from django.contrib.auth import get_user_model
from django.contrib.contenttypes.fields import GenericForeignKey, GenericRelation
from django.contrib.contenttypes.models import ContentType
from django.contrib.postgres.fields import ArrayField
from django.core.exceptions import ValidationError
from django.core.validators import FileExtensionValidator, RegexValidator
from django.db import models
from django.db.models import CheckConstraint, Q
from django.urls.base import reverse
from django.utils.translation import gettext_lazy as _
from django_countries.fields import CountryField
import reversion
from reversion.models import Revision

from core.constants import AC_STRUCTURE, BSV_STRUCTURE, MUS_STRUCTURE, SEVES_STRUCTURE
from seves import settings

from .managers import (
    ContactManager,
    ContactQueryset,
    DocumentManager,
    DocumentQueryset,
    LienLibreQueryset,
    MessageManager,
    MessagQueryset,
    StructureQueryset,
)
from .soft_delete_mixins import AllowsSoftDeleteMixin
from .storage import get_timestamped_filename, get_timestamped_filename_export
from .validators import AllowedExtensions, AnyOfValidator, MagicMimeValidator, validate_numero_agrement

User = get_user_model()


def user_is_referent_national(user: User):
    return settings.REFERENT_NATIONAL_GROUP in user.groups.values_list("name", flat=True)


class Agent(models.Model):
    class Meta:
        verbose_name = "Agent"
        verbose_name_plural = "Agents"
        indexes = [
            models.Index(fields=["user"]),
        ]
        ordering = ["nom", "prenom"]

    user = models.OneToOneField(User, on_delete=models.RESTRICT)
    structure = models.ForeignKey("Structure", on_delete=models.RESTRICT)
    structure_complete = models.CharField(max_length=255)
    prenom = models.CharField(max_length=255)
    nom = models.CharField(max_length=255)
    fonction_hierarchique = models.CharField(max_length=255, blank=True)
    complement_fonction = models.TextField(blank=True)
    telephone = models.CharField(max_length=20, blank=True)
    mobile = models.CharField(max_length=20, blank=True)

    def __str__(self):
        return f"{self.nom} {self.prenom}"

    def is_in_structure(self, structure):
        return self.structure == structure

    @property
    def agent_with_structure(self):
        return f"{self.nom} {self.prenom} ({self.structure})"


class Structure(models.Model):
    class Meta:
        verbose_name = "Structure"
        verbose_name_plural = "Structures"
        ordering = ["niveau1", "niveau2"]

    niveau1 = models.CharField(max_length=255)
    niveau2 = models.CharField(max_length=255, blank=True)
    libelle = models.CharField(max_length=255, blank=True)

    force_can_be_contacted = models.BooleanField(default=False)

    objects = StructureQueryset.as_manager()

    def __str__(self):
        return self.libelle

    @property
    def is_ac(self):
        "Permet de savoir si la structure fait partie de l'administration centrale (AC)"
        return self.niveau1 == AC_STRUCTURE

    @property
    def is_mus(self):
        return self.niveau2 == MUS_STRUCTURE

    @property
    def is_mus_or_bsv(self):
        return self.niveau2 in [MUS_STRUCTURE, BSV_STRUCTURE]

    @property
    def is_seves(self):
        return self.niveau1 == SEVES_STRUCTURE


@reversion.register()
class Contact(models.Model):
    class Meta:
        verbose_name = "Contact"
        verbose_name_plural = "Contacts"
        indexes = [
            models.Index(fields=["email", "structure", "agent"]),
        ]
        ordering = ["structure", "agent"]
        constraints = [
            models.CheckConstraint(
                condition=(
                    (Q(structure__isnull=False) & Q(agent__isnull=True))
                    | (Q(structure__isnull=True) & Q(agent__isnull=False))
                ),
                name="contact_has_structure_or_agent",
            ),
            models.CheckConstraint(
                condition=(
                    Q(agent__isnull=True)
                    | (
                        Q(email__isnull=False)
                        & ~Q(email="")
                        & (Q(sv_email="") | Q(sv_email__isnull=True))
                        & (Q(ssa_email="") | Q(ssa_email__isnull=True))
                        & (Q(tiac_email="") | Q(tiac_email__isnull=True))
                    )
                ),
                name="contact_agent_email_only",
            ),
        ]

    structure = models.ForeignKey(Structure, on_delete=models.RESTRICT, null=True, blank=True)
    agent = models.ForeignKey(Agent, on_delete=models.RESTRICT, null=True, blank=True)
    email = models.EmailField()

    sv_email = models.EmailField(null=True, blank=True)
    ssa_email = models.EmailField(null=True, blank=True)
    tiac_email = models.EmailField(null=True, blank=True)

    objects = ContactManager.from_queryset(ContactQueryset)()

    def __str__(self):
        return str(self.structure) if self.structure else str(self.agent)

    def get_email_for_object(self, obj):
        app_name = obj._meta.app_label
        if hasattr(self, f"{app_name}_email"):
            return getattr(self, f"{app_name}_email") or self.email
        return self.email

    @property
    def display_with_agent_unit(self):
        return (
            str(self.structure) if self.structure else f"{self.agent.nom} {self.agent.prenom} ({self.agent.structure})"
        )

    def get_structure_contact(self):
        """Retourne le contact de la structure associée si ce contact est lié à un agent."""
        if self.agent:
            return self.agent.structure.contact_set.first()


class FinSuiviContact(models.Model):
    content_type = models.ForeignKey(ContentType, on_delete=models.CASCADE)
    object_id = models.PositiveIntegerField()
    content_object = GenericForeignKey("content_type", "object_id")
    contact = models.ForeignKey(Contact, on_delete=models.CASCADE)

    class Meta:
        constraints = [
            models.UniqueConstraint(fields=["content_type", "object_id", "contact"], name="unique_fin_suivi_contact")
        ]

    def __str__(self):
        return f"Fin de suivi de {self.contact} pour la fiche {self.content_type} n° {self.content_object}"

    @classmethod
    def _can_change_fin_de_suivi(cls, object, user, contact):
        if not hasattr(object, "contacts"):
            return False
        if contact not in object.contacts.all():
            return False
        if not object.can_user_access(user):
            return False

    @classmethod
    def can_add_fin_de_suivi(cls, object, user):
        contact = user.agent.structure.contact_set.all()[0]
        content_type = ContentType.objects.get_for_model(object).id
        can_change_fin_de_suivi = cls._can_change_fin_de_suivi(object, user, contact)
        if can_change_fin_de_suivi is False:
            return False

        return not FinSuiviContact.objects.filter(
            object_id=object.id, content_type_id=content_type, contact=contact
        ).exists()

    @classmethod
    def can_remove_fin_de_suivi(cls, object, user):
        contact = user.agent.structure.contact_set.all()[0]
        content_type = ContentType.objects.get_for_model(object).id
        can_change_fin_de_suivi = cls._can_change_fin_de_suivi(object, user, contact)
        if can_change_fin_de_suivi is False:
            return False

        return FinSuiviContact.objects.filter(
            object_id=object.id, content_type_id=content_type, contact=contact
        ).exists()

    def clean(self):
        super().clean()
        content_type_model = self.content_type.model
        fiche_model = apps.get_model(self.content_type.app_label, content_type_model)
        fiche_object = fiche_model.objects.get(id=self.object_id)
        if not hasattr(fiche_object, "contacts"):
            raise ValidationError(f"La fiche {fiche_model} liée ne possède pas de relation 'contacts'.")
        if self.contact.agent:
            raise ValidationError("Le contact doit être lié à une structure et non à un agent.")
        if not fiche_object.contacts.filter(id=self.contact.id).exists():
            raise ValidationError(
                "Vous ne pouvez pas signaler la fin de suivi pour cette fiche car votre structure n'est pas dans la liste des contacts."
            )


@reversion.register()
class Document(models.Model):
    class TypeDocument(models.TextChoices):
        ARRETE = "arrete_prefectoral_ministériel", "Arrêté préfectoral/ministériel"
        AUTRE = "autre", "Autre document"
        CARTOGRAPHIE = "cartographie", "Cartographie"
        CERTIFICAT_PHYTOSANITAIRE = "certificat_phytosanitaire", "Certificat phytosanitaire"
        COMPTE_RENDU_REUNION = "compte_rendu_reunion", "Compte rendu de réunion"
        COURRIER_OFFICIEL = "courrier_officiel", "Courrier officiel"
        DSCE = "dsce", "DSCE"
        FACTURE = "facture", "Facture"
        IMAGE = "image", "Image"
        PASSEPORT_PHYTOSANITAIRE = "passeport_phytosanitaire", "Passeport phytosanitaire"
        RAPPORT_ANALYSE = "rapport_analyse", "Rapport d'analyse"
        RAPPORT_INSPECTION = "rapport_inspection", "Rapport d'inspection"
        REGLEMENTATION = "reglementation", "Réglementation"
        TRANSPORT = "document_de_transport", "Document de transport"
        TRACABILITE = "tracabilité", "Traçabilité"

        SIGNALEMENT_CERFA = "cerfa", "Signalement/notification : Cerfa"
        SIGNALEMENT_RASFF = "fiche_rasff", "Signalement/notification : Fiche RASFF"
        SIGNALEMENT_AUTRE = "signalement_autre", "Signalement/notification : Autre"
        SIGNALEMENT_MULTIPLE = (
            "signalement_multiple",
            "Signalement/notification : Cerfa, DO ARS, Autre",
        )
        ENQUETE = "enquete_alimentaire", "Enquête alimentaire de l’ARS/SpF"
        MENU = "menu", "Menu"
        ANALYSE_RISQUE = "analyse_risque", "Analyse de risque"

core/templates/core/_contact_checkbox.html
<div class="fr-fieldset__element">
    <div class="fr-checkbox-group">
        <input name="contacts" id="checkboxes-{{ checkbox_id }}" type="checkbox" value="{{ contact.id }}" aria-describedby="checkboxes-{{ checkbox_id }}-messages">
        <label class="fr-label" for="checkboxes-{{ checkbox_id }}">
            {% if contact.agent %}
                {{ contact.agent.nom }} {{ contact.agent.prenom }}{% if contact.agent.fonction_hierarchique %} ({{ contact.agent.fonction_hierarchique }}){% endif %}
            {% else %}
                {{ contact.structure }}
            {% endif %}
        </label>
    </div>
</div>

core/templates/core/_details_toogle.html
<div data-fiche-id="{{ pk }}">
    <fieldset class="fr-segmented">
        <div class="fr-segmented__elements">
            <div class="fr-segmented__element">
                <input value="detail" checked type="radio" id="detail-btn" name="segmented-2215">
                <label class="fr-label" for="detail-btn"><i class="ri-expand-vertical-fill fr-mr-1w"></i>Affichage détaillé</label>
            </div>
            <div class="fr-segmented__element">
                <input value="synthese" type="radio" id="synthese-btn" name="segmented-2215">
                <label class="fr-label" for="synthese-btn"><i class="ri-collapse-vertical-fill fr-mr-1w"></i>Synthèse</label>
            </div>
        </div>
    </fieldset>
</div>

core/templates/core/_document_warning_modal.html
<!-- bouton relié à la modal en display non -> https://github.com/GouvernementFR/dsfr/issues/728 -->
<button type="button" class="fr-hidden" data-fr-opened="false" aria-controls="fr-modal-document-confirmation"></button>
<dialog aria-labelledby="fr-modal-title-document-confirmation" role="dialog" id="fr-modal-document-confirmation" class="fr-modal">
    <div class="fr-container fr-container--fluid fr-container-md">
        <div class="fr-grid-row fr-grid-row--center">
            <div class="fr-col-12 fr-col-md-8 fr-col-lg-6">
                <div class="fr-modal__body">
                    <div class="fr-modal__header">
                        <button class="fr-btn--close fr-btn" title="Fermer la fenêtre modale" aria-controls="fr-modal-document-confirmation">Fermer</button>
                    </div>
                    <div class="fr-modal__content">
                        <h1 id="fr-modal-title-document-confirmation" class="fr-modal__title"><span class="fr-icon-arrow-right-line fr-icon--lg"></span>Document non ajouté</h1>
                        <p>Vous n'avez pas validé l'ajout du document, que souhaitez-vous faire&nbsp;?</p>

                        <button type="button" class="fr-btn fr-btn--secondary" id="send-without-adding-document">Envoyer le message sans document</button>
                        <button type="button" class="fr-btn" id="send-with-adding-document">Valider et envoyer</button>
                    </div>
                </div>
            </div>
        </div>
    </div>
</dialog>

core/templates/core/_evenement_sort_link.html
<a href="?order_by={{ field }}{% if field == current_order_by and current_order_dir == 'asc' %}&order_dir=desc{% else %}&order_dir=asc{% endif %}{% for key, value in request.GET.items %}{% if key != 'order_by' and key != 'order_dir' and key != 'page' %}&{{ key }}={{ value }}{% endif %}{% endfor %}" class="evenements__sort-link">
    {{ display_name }}
    {% if field == current_order_by %}
        <span class="fr-icon--sm {% if current_order_dir == 'asc' %}fr-icon-arrow-up-line{% else %}fr-icon-arrow-down-line{% endif %}" aria-hidden="true"></span>
    {% endif %}
</a>

core/templates/core/_messages.html
<div class="fr-my-1w document-messages">
    {% if messages %}
        {% for message in messages %}
            {% if value in message.extra_tags %}
                <div class="fr-alert fr-alert--{{ message.level_tag }}">
                    <h3 class="fr-alert__title">{{ message }}</h3>
                    <button class="fr-btn--close fr-btn btn--close-js" title="Masquer le message">
                        Masquer le message
                    </button>
                </div>
            {% endif %}
        {% endfor %}
    {% endif %}
</div>

core/templates/core/_show_form_errors.html
<div class="fr-alert fr-alert--error fr-mb-4w {{ classes }}">
    {% for error in errors %}
        <p>{{ error }}</p>
    {% endfor %}
    <button class="fr-btn--close fr-btn btn--close-js" title="Masquer le message">
        Masquer le message
    </button>
</div>

core/templates/core/base.html
{% load partials dsfr_tags %}
{% load static importmap dsfr_tags groups waffle_tags %}

<!doctype html>
<html lang="fr">
    <head>
        <meta charset="utf-8">
        <meta name="format-detection" content="telephone=no">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
        <meta name="siret-api-endpoint" content="{{ siret_api_endpoint }}">
        {% importmap nonce=request.csp_nonce %}
        {% dsfr_css %}
        <link rel="stylesheet" href="{% static 'dsfr/dist/utility/icons/icons.min.css' %}">
        {% dsfr_favicon %}
        <title>Sèves</title>
        <link rel="stylesheet" href="{% static 'core/base.css' %}">
        <link rel="stylesheet" href="{% static 'core/liens_libres.css' %}">
        <link rel="stylesheet" href="{% static 'core/bloc_commun.css' %}">
        <link rel="stylesheet" href="{% static 'core/message.css' %}">
        <link rel="stylesheet" href="{% static 'core/fil_de_suivi.css' %}">
        <link rel="stylesheet" href="{% static 'core/contact_list.css' %}">
        <link rel="stylesheet" href="{% static 'core/contact_add_form.css' %}">
        <link rel="stylesheet" href="{% static 'core/document_form.css' %}">
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/choices.js@11.0.4/public/assets/styles/choices.min.css" />
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/remixicon@4.3.0/fonts/remixicon.css"/>
        {% if media %}{% for tag in media.render_css %}{{ tag }}{% endfor %}{% endif %}
        {% block base_override %}{% endblock %}
        {% block extrahead %}{% endblock %}
    </head>

    <body class="{{ environment_class }}">
        {% block aside %}
        {% endblock aside %}
        <header role="banner" class="fr-header">
            <div class="fr-header__body">
                <div class="fr-px-1w">
                    <div class="fr-header__body-row">
                        <div class="fr-header__brand">
                            <div class="fr-header__brand-top">
                                <img src="{% static 'images/marianne.png' %}" alt="">
                                <div class="fr-header__navbar">
                                    <button class="fr-btn--menu fr-btn" data-fr-opened="false" aria-controls="modal-499"
                                            id="button-500" title="Menu"> Menu
                                    </button>
                                </div>
                            </div>
                            <div class="fr-header__service">
                                <p class="fr-header__service-title"> Sèves </p>
                            </div>
                            <div class="product-switch">
                                {% block product %}
                                    {% if current_domain %}
                                        {% if other_domains|length == 0 %}
                                            <a href="{{ current_domain.url }}" class="fr-tag {{ current_domain.icon }} fr-tag--icon-left">
                                                {{ current_domain.nom }}
                                            </a>
                                        {% else %}
                                            <nav role="navigation" class="fr-translate fr-nav">
                                                <div class="fr-nav__item">
                                                    <button class="fr-translate__btn fr-btn fr-btn--tertiary fr-tag fr-tag--icon-left"
                                                            aria-controls="domain-picker" aria-expanded="false"
                                                            title="Sélectionner un produit">
                                                        <span class="{{ current_domain.icon }} fr-icon--sm fr-pr-1w" ></span>
                                                        {{ current_domain.nom }}</button>
                                                    <div class="fr-collapse fr-translate__menu fr-menu" id="domain-picker">
                                                        <ul class="fr-menu__list">
                                                            {% for domain in other_domains %}
                                                                <li class="fr-mt-1w">
                                                                    <a class="fr-translate__language fr-nav__link fr-tag" href="{{ domain.url }}" >
                                                                        <span class="{{ domain.icon }} fr-icon--sm fr-pr-1w" ></span>
                                                                        {{ domain.nom }}
                                                                    </a>
                                                                </li>
                                                            {% endfor %}
                                                        </ul>
                                                    </div>
                                                </div>
                                            </nav>
                                        {% endif %}
                                    {% endif %}


                                {% endblock product %}
                            </div>
                        </div>
                        <div class="fr-header__tools">
                            <div class="fr-header__tools-links">
                                {% if user.is_authenticated %}
                                    <ul class="fr-btns-group">
                                        {% block product_nav %}
                                        {% endblock product_nav %}
                                        {% if current_domain.help_url %}
                                            <li>
                                                <a class="fr-btn" href="{{ current_domain.help_url }}" target="_blank">Aide</a>
                                            </li>
                                        {% endif %}
                                        <li class="fr-nav__item">
                                            {% if user.is_authenticated %}
                                                <button class="fr-nav__btn" aria-expanded="false" aria-controls="menu-777"><span class="fr-icon-account-circle-line"></span>{{ user.email }}</button>
                                                <div class="fr-collapse fr-menu" id="menu-777">
                                                    <ul class="fr-menu__list">
                                                        <li>
                                                            <form action="{% url 'oidc_logout' %}" method="post">
                                                                {% csrf_token %}
                                                                <input type="submit" value="Se déconnecter" class="fr-nav__link">
                                                            </form>
                                                        </li>
                                                        {% if request.user|has_group:"access_admin" %}
                                                            <li class="fr-nav__link"><a href="{% url 'handle-permissions' %}">Gestion des droits d'accès</a></li>
                                                        {% endif %}
                                                        {% if request.user.agent.structure.is_mus %}
                                                            <li class="fr-nav__link"><a href="{% url 'handle-admins' %}">Gestion des administrateurs</a></li>
                                                        {% endif %}
                                                    </ul>
                                                </div>
                                            {% endif %}
                                        </li>
                                    </ul>
                                {% endif %}
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="fr-header__menu fr-modal" id="modal-499" aria-labelledby="button-500">
                <div class="fr-container">
                    <button class="fr-btn--close fr-btn" aria-controls="modal-499" title="Fermer"> Fermer</button>
                    <div class="fr-header__menu-links"></div>
                </div>
            </div>
        </header>

        {% if request.user.agent.structure.is_seves and env == "prod" %}
            <div class="prod-warning-message">
                {% dsfr_notice title="Attention vous êtes sur l'environnement de production de Sèves" type="alert" %}
            </div>
        {% endif %}

        {% if messages %}
            <div class="alert-container">
                {% for message in messages %}
                    {% if "core" not in message.extra_tags and "blocking" not in message.extra_tags %}
                        <div class="fr-alert fr-alert--{{ message.level_tag }}">
                            <h3 class="fr-alert__title">{{message}}</h3>
                            <button class="fr-btn--close fr-btn btn--close-js" title="Masquer le message">
                                Masquer le message
                            </button>
                        </div>
                    {% endif %}
                {% endfor %}
            </div>
        {% endif %}

        {% for message in messages %}
            {% if "blocking" in message.extra_tags %}
                {% include "core/_modale_erreur_bloquante.html" %}
            {% endif %}
        {% endfor %}

        {% block content %}{% endblock %}

        <div class="footer-links fr-mb-2w">
            <a class="fr-link fr-mr-1w" href="{% url 'mentions-legales' %}">Mentions légales</a>
            <a class="fr-link fr-mr-1w" href="{% url 'politique-de-confidentialite' %}">Politique de confidentialité</a>
            Accessibilité : non conforme
        </div>

        {% dsfr_js nonce=request.csp_nonce %}
        <script type="text/javascript" src="{% static 'core/base.js' %}"></script>
        {% if media %}{% for tag in media.render_js %}{{ tag }}{% endfor %}{% endif %}
        {# Kept for compatibility for now #}
        <script src="https://cdn.jsdelivr.net/npm/choices.js@11.0.4/public/assets/scripts/choices.min.js"></script>
        {% block scripts %}{% endblock %}
    </body>

</html>