seves/urls.py
from django.conf import settings
from django.urls import include, path
from django.views.generic.base import RedirectView
from mozilla_django_oidc.urls import OIDCCallbackClass

urlpatterns = [
    path("", RedirectView.as_view(pattern_name="sv:evenement-liste"), name="index"),
    path("login-eap-callback", OIDCCallbackClass.as_view(), name="custom_oidc_authentication_callback"),
    path("sv/", include("sv.urls", namespace="sv")),
    path("ssa/", include("ssa.urls", namespace="ssa")),
    path("tiac/", include("tiac.urls", namespace="tiac")),
    path("core/", include("core.urls"), name="core"),
    path("account/", include("account.urls"), name="account"),
    path("oidc/", include("mozilla_django_oidc.urls")),
]

if settings.ADMIN_ENABLED:
    from django.contrib import admin

    admin.site.site_header = "Administration de Sèves"
    admin.site.site_title = "Sèves"
    admin.site.index_title = "Bienvenue sur l'administration de Sèves"
    urlpatterns += [
        path(f"{settings.ADMIN_URL}/", admin.site.urls),
    ]

if settings.DEBUG and settings.ENVIRONMENT != "test":
    urlpatterns.append(path("__debug__/", include("debug_toolbar.urls")))

sv/urls.py
from django.urls import path

from .api_views import search_espece_echantillon
from .views import (
    EvenementDetailView,
    EvenementListView,
    EvenementUpdateView,
    EvenementVisibiliteUpdateView,
    FicheDetectionCreateView,
    FicheDetectionExportView,
    FicheDetectionUpdateView,
    FicheZoneDelimiteeCreateView,
    FicheZoneDelimiteeDeleteView,
    FicheZoneDelimiteeUpdateView,
    VisibiliteStructureView,
)

app_name = "sv"
urlpatterns = [
    path(
        "evenements/",
        EvenementListView.as_view(),
        name="evenement-liste",
    ),
    path(
        "evenement/<str:numero>/",
        EvenementDetailView.as_view(),
        name="evenement-details",
    ),
    path(
        "evenement/<int:pk>/modification/",
        EvenementUpdateView.as_view(),
        name="evenement-update",
    ),
    path(
        "fiches-detection/creation/",
        FicheDetectionCreateView.as_view(),
        name="fiche-detection-creation",
    ),
    path(
        "fiches-detection/export/",
        FicheDetectionExportView.as_view(),
        name="fiche-detection-export",
    ),
    path(
        "fiches-detection/<int:pk>/modification/",
        FicheDetectionUpdateView.as_view(),
        name="fiche-detection-modification",
    ),
    path(
        "evenement/<int:pk>/visibilite/",
        EvenementVisibiliteUpdateView.as_view(),
        name="evenement-visibilite-update",
    ),
    path(
        "api/espece/recherche/",
        search_espece_echantillon,
        name="api-search-espece",
    ),
    path(
        "fiche-zone-delimitee/creation/",
        FicheZoneDelimiteeCreateView.as_view(),
        name="fiche-zone-delimitee-creation",
    ),
    path(
        "fiche-zone-delimitee/<int:pk>/modification/",
        FicheZoneDelimiteeUpdateView.as_view(),
        name="fiche-zone-delimitee-update",
    ),
    path(
        "evenement/<int:pk>/structures/ajout/visibilite",
        VisibiliteStructureView.as_view(),
        name="structure-add-visibilite",
    ),
    path(
        "fiche-zone-delimitee/<int:pk>/delete/",
        FicheZoneDelimiteeDeleteView.as_view(),
        name="fiche-zone-delimitee-delete",
    ),
]

tiac/urls.py
from django.urls import path

from tiac import views
from tiac.views import TiacExportView

app_name = "tiac"
urlpatterns = [
    path(
        "evenements/",
        views.TiacListView.as_view(),
        name="evenement-liste",
    ),
    path(
        "evenement-simple/creation",
        views.EvenementSimpleCreationView.as_view(),
        name="evenement-simple-creation",
    ),
    path(
        "investigation-tiac/creation",
        views.InvestigationTiacCreationView.as_view(),
        name="investigation-tiac-creation",
    ),
    path(
        "investigation-tiac/edition/<int:pk>",
        views.InvestigationTiacUpdateView.as_view(),
        name="investigation-tiac-edition",
    ),
    path(
        "evenement-simple/<str:numero>/",
        views.EvenementSimpleDetailView.as_view(),
        name="evenement-simple-details",
    ),
    path(
        "evenement-simple/<int:pk>/transfer",
        views.EvenementSimpleTransferView.as_view(),
        name="evenement-simple-transfer",
    ),
    path(
        "evenement-simple/<int:pk>/transform-investigation",
        views.EvenementTransformView.as_view(),
        name="transform-investigation",
    ),
    path(
        "evenement-simple/<int:pk>/edition",
        views.EvenementSimpleUpdateView.as_view(),
        name="evenement-simple-edition",
    ),
    path(
        "investigation-tiac/<str:numero>/",
        views.InvestigationTiacDetailView.as_view(),
        name="investigation-tiac-details",
    ),
    path(
        "evenement-simple/<str:numero>/document/",
        views.EvenementSimpleDocumentExportView.as_view(),
        name="export-evenement-simple-document",
    ),
    path(
        "investigation-tiac/<str:numero>/document/",
        views.InvestigationTiacExportView.as_view(),
        name="export-investigation-tiac-document",
    ),
    path(
        "export/tiac/",
        TiacExportView.as_view(),
        name="export-tiac",
    ),
]

ssa/models/etablissement.py
from django.db import models
import reversion

from core.models import BaseEtablissement


class PositionDossier(models.TextChoices):
    DETECTION_NON_CONFORMITE = "detection_non_conformite", "Détection de la non-conformité"
    SURVENUE_NON_CONFORMITE = "survenue_non_conformite", "Survenue de la non-conformité"
    DETECTION_ET_SURVENUE_NON_CONFORMITE = (
        "detection_et_survenue_non_conformite",
        "Détection et survenue de la non-conformité",
    )
    AUTRE_MAILLON_CHAINE_DISTRIBUTION = (
        "autre_maillon_chaine_distribution",
        "Autre maillon de la chaîne de distribution",
    )
    AUTRE = "autre", "Autre"


@reversion.register()
class Etablissement(BaseEtablissement, models.Model):
    evenement_produit = models.ForeignKey(
        "ssa.EvenementProduit", on_delete=models.PROTECT, related_name="etablissements", null=True, default=None
    )

    investigation_cas_humain = models.ForeignKey(
        "ssa.EvenementInvestigationCasHumain",
        on_delete=models.PROTECT,
        related_name="etablissements",
        null=True,
        default=None,
    )

    type_exploitant = models.CharField(max_length=45, verbose_name="Type exploitant", blank=True)
    position_dossier = models.CharField(
        max_length=100, choices=PositionDossier.choices, verbose_name="Position dossier", blank=True
    )
    numeros_resytal = models.CharField(max_length=255, verbose_name="Numéros d’inspection Resytal", blank=True)

    historical_data = models.JSONField(default=dict, blank=True)

    def __str__(self):
        return f"{self.raison_sociale}"

    def save(self, *args, **kwargs):
        with reversion.create_revision():
            super().save(*args, **kwargs)

    @classmethod
    def get_position_dossier_css_class(self, value):
        IMPORTANT_CASES = [
            PositionDossier.SURVENUE_NON_CONFORMITE,
            PositionDossier.DETECTION_NON_CONFORMITE,
            PositionDossier.DETECTION_ET_SURVENUE_NON_CONFORMITE,
        ]
        return "fr-badge--info" if value in IMPORTANT_CASES else ""

    @property
    def position_dossier_css_class(self):
        return self.get_position_dossier_css_class(self.position_dossier)

    class Meta:
        constraints = (
            models.CheckConstraint(
                condition=(
                    models.Q(evenement_produit__isnull=False, investigation_cas_humain__isnull=True)
                    | models.Q(evenement_produit__isnull=True, investigation_cas_humain__isnull=False)
                ),
                name="either_evenement_produit_or_investigation_cas_humain",
            ),
        )

tiac/models.py
from dirtyfields import DirtyFieldsMixin
from django.contrib.postgres.fields import ArrayField
from django.core.validators import RegexValidator
from django.db import models, transaction
from django.db.models import Q
from django.urls import reverse
from django.utils.html import strip_tags
import reversion
from reversion.models import Version

from core.mixins import (
    AllowModificationMixin,
    EmailNotificationMixin,
    WithContactPermissionMixin,
    WithDocumentPermissionMixin,
    WithEtatMixin,
    WithFreeLinkIdsMixin,
    WithMessageUrlsMixin,
)
from core.model_mixins import WithBlocCommunFieldsMixin
from core.models import BaseEtablissement, Departement, Document, Structure
from core.soft_delete_mixins import AllowsSoftDeleteMixin
from ssa.constants import CategorieDanger, CategorieProduit
from tiac.constants import (
    DANGERS_COURANTS,
    SELECTED_HAZARD_CHOICES,
    EtatPrelevement,
    EvenementFollowUp,
    EvenementOrigin,
    ModaliteDeclarationEvenement,
    Motif,
    MotifAliment,
    TypeAliment,
    TypeCollectivite,
    TypeRepas,
)

from .constants import DangersSyndromiques, SuspicionConclusion
from .managers import EvenementSimpleManager, InvestigationTiacManager
from .model_mixins import WithSharedNumeroMixin


class BaseTiacModel(models.Model):
    createur = models.ForeignKey(Structure, on_delete=models.PROTECT, verbose_name="Structure créatrice")
    date_creation = models.DateTimeField(auto_now_add=True, verbose_name="Date de création")
    date_reception = models.DateField(verbose_name="Date de réception")
    evenement_origin = models.CharField(
        choices=EvenementOrigin.choices, verbose_name="Signalement déclaré par", blank=True
    )
    modalites_declaration = models.CharField(
        choices=ModaliteDeclarationEvenement.choices,
        default=ModaliteDeclarationEvenement.SIGNAL_CONSO,
        verbose_name="Modalités de déclaration",
        blank=True,
    )
    contenu = models.TextField(verbose_name="Contenu du signalement")
    notify_ars = models.BooleanField(default=False, verbose_name="ARS informée")

    class Meta:
        abstract = True

    def get_allowed_document_types(self):
        return [
            Document.TypeDocument.SIGNALEMENT_MULTIPLE,
            Document.TypeDocument.ENQUETE,
            Document.TypeDocument.MENU,
            Document.TypeDocument.RAPPORT_ANALYSE,
            Document.TypeDocument.FICHE_PRODUIT,
            Document.TypeDocument.TRACABILITE_INTERNE_TABLEAU,
            Document.TypeDocument.TRACABILITE_INTERNE_JUSTIFICATIF,
            Document.TypeDocument.TRACABILITE_AVAL_JUSTIFICATIF,
            Document.TypeDocument.TRACABILITE_AVAL_AUTRE,
            Document.TypeDocument.DSCE_CHED,
            Document.TypeDocument.CERTIFICAT_SANITAIRE,
            Document.TypeDocument.ETIQUETAGE,
            Document.TypeDocument.PHOTO,
            Document.TypeDocument.COMMUNIQUE_PRESSE,
            Document.TypeDocument.COURRIERS_COURRIELS,
            Document.TypeDocument.SUITES_ADMINISTRATIVES,
            Document.TypeDocument.COMPTE_RENDU,
            Document.TypeDocument.AUTRE,
        ]


@reversion.register()
class EvenementSimple(
    AllowsSoftDeleteMixin,
    AllowModificationMixin,
    WithContactPermissionMixin,
    WithEtatMixin,
    WithSharedNumeroMixin,
    WithFreeLinkIdsMixin,
    WithBlocCommunFieldsMixin,
    WithDocumentPermissionMixin,
    WithMessageUrlsMixin,
    EmailNotificationMixin,
    BaseTiacModel,
    models.Model,
):
    nb_sick_persons = models.IntegerField(verbose_name="Nombre de malades total", null=True)

    follow_up = models.CharField(
        choices=EvenementFollowUp.choices, default=EvenementFollowUp.NONE, verbose_name="Suite donnée"
    )
    transfered_to = models.ForeignKey(Structure, on_delete=models.PROTECT, related_name="transfered", null=True)

    objects = EvenementSimpleManager()

    def save(self, *args, **kwargs):
        with transaction.atomic():
            with reversion.create_revision():
                if not self.numero_annee and not self.numero_evenement:
                    annee, numero = EvenementSimple._get_annee_and_numero()
                    self.numero_annee = annee
                    self.numero_evenement = numero
                super().save(*args, **kwargs)

    @property
    def numero(self):
        return f"T-{self.numero_annee}.{self.numero_evenement}"

    def __str__(self):
        return self.numero

    def get_absolute_url(self):
        numero = f"{self.numero_annee}.{self.numero_evenement}"
        return reverse("tiac:evenement-simple-details", kwargs={"numero": numero})

    @property
    def latest_version(self):
        return (
            Version.objects.get_for_object(self)
            .select_related("revision")
            .select_related("revision__user__agent__structure")
            .first()
        )

    def can_user_delete(self, user):
        return self.can_user_access(user)

    def can_be_transfered(self, user):
        return self.can_user_access(user) and self.is_published

    def can_be_changed_in_investigation(self, user):
        return self.can_user_access(user)

    def get_soft_delete_success_message(self):
        return f"L'évènement {self.numero} a bien été supprimé"

    def get_cloture_confirm_message(self):
        return f"L'événement n°{self.numero} a bien été clôturé."

    def get_soft_delete_confirm_title(self):
        return f"Supprimer l'événement {self.numero}"

    def get_soft_delete_confirm_message(self):
        return "Cette action est irréversible. Confirmez-vous la suppression de cet évènement ?"

    def get_crdi_form(self):
        from ssa.forms import CompteRenduDemandeInterventionForm

        return CompteRenduDemandeInterventionForm

    @property
    def limit_contacts_to_user_from_app(self):
        return "ssa"

    def get_publish_success_message(self):
        return "Événement simple publié avec succès"

    def _user_can_interact(self, user):
        return not self.is_cloture and self.can_user_access(user)

    def get_email_subject(self):
        return f"Enregistrement simple {self.numero}"

    @property
    def type_evenement(self):
        return "Enregistrement simple"

    @property
    def display_transfer_notice(self):
        return self.follow_up == EvenementFollowUp.INVESGTIGATION_TIAC

    @property
    def display_evenement_produit_notice(self):
        return self.follow_up == EvenementFollowUp.PASSE_EVENEMENT_PRODUIT

    def get_short_email_display_name(self):
        return f"Enregistrement simple {self.numero}"

    def get_long_email_display_name(self):
        return f"Enregistrement simple {self.numero}"

    def get_long_email_display_name_as_html(self):
        return f"<b>Enregistrement simple {self.numero}</b>"


class Evaluation(models.TextChoices):
    SATISFAISANTE = "satisfaisante", "A - Maîtrise des risques satisfaisante"
    ACCEPTABLE = "acceptable", "B - Maîtrise des risques acceptable"
    MISE_EN_DEMEURE = "mise en demeure", "C - Maîtrise des risques insatisfaisante - Mise en demeure"
    RESTRICTION = "restriction", "C - Maîtrise des risques insatisfaisante - Restriction d'activité"
    PERTE_DE_MAITRISE = "perte de maitrise", "D - Perte de maîtrise des risques - Fermeture ou restriction d'activité"


validate_resytal = RegexValidator(
    regex=r"^\d{2}-\d{6}$",
    message="Le numéro Resytal doit être au format AA-XXXXXX ; par exemple : 19-067409",
    code="invalid_resytal",
)


@reversion.register()
class Etablissement(BaseEtablissement, models.Model):
    evenement_simple = models.ForeignKey(
        EvenementSimple, null=True, default=None, on_delete=models.PROTECT, related_name="etablissements"
    )
    investigation = models.ForeignKey(
        "tiac.InvestigationTiac", null=True, default=None, on_delete=models.PROTECT, related_name="etablissements"
    )

    type_etablissement = models.CharField(max_length=45, verbose_name="Type d'établissement", blank=True)

    has_inspection = models.BooleanField(default=False, verbose_name="Inspection")
    numero_resytal = models.CharField(blank=True, verbose_name="Numéro Resytal", validators=[validate_resytal])
    date_inspection = models.DateField(blank=True, null=True, default=None, verbose_name="Date d'inspection")
    evaluation = models.CharField(choices=Evaluation.choices, blank=True, verbose_name="Évaluation globale")
    commentaire = models.TextField(verbose_name="Commentaire", blank=True)

    def __str__(self):
        return f"{self.raison_sociale}"

    def save(self, *args, **kwargs):
        with reversion.create_revision():
            super().save(*args, **kwargs)

    class Meta:
        constraints = [
            models.CheckConstraint(
                condition=(
                    Q(has_inspection=True)
                    | (Q(numero_resytal="") & Q(evaluation="") & Q(commentaire="") & Q(date_inspection=None))
                ),
                name="inspection_required_for_inspection_related_fields",
            ),
            models.CheckConstraint(
                condition=(
                    (Q(evenement_simple__isnull=True) & Q(investigation__isnull=False))
                    | (Q(evenement_simple__isnull=False) & Q(investigation__isnull=True))
                ),
                name="is_related_to_either_evenement_simple_or_investigation_tiac",
            ),
        ]

    @property
    def address_summary(self):
        value = ""
        if self.commune:
            value = self.commune
        if self.departement:
            value += f" ({self.departement.numero}) | {self.departement.nom}"
        return value


class InvestigationFollowUp(models.TextChoices):
    INVESTIGATION_DD = "investigation par ma dd", "Investigation locale"
    INVESTIGATION_COORDONNEE = "investigation coordonnée", "Investigation coordonnée / MUS informée"


class Analyses(models.TextChoices):
    OUI = "oui", "Oui"
    NON = "non", "Non"

tiac/templates/tiac/_investigation_tiac_informations.html
{% load or_empty_value_tag %}
<div class="white-container detail-content">
  <h2 class="fr-h6">Le contexte</h2>
  <div class="fr-container--fluid">
    <div class="fr-grid-row fr-grid-row--gutters">
      <div class="fr-col-3">
        <div class="fr-container--fluid">
          <div class="fr-grid-row fr-grid-row--gutters">
            <div class="fr-col-7 bold">Créateur</div>
            <div class="fr-col-5">{{ object.createur }}</div>
          </div>
          <div class="fr-grid-row fr-grid-row--gutters">
            <div class="fr-col-7 bold">Date de réception</div>
            <div class="fr-col-5">{{ object.date_reception|date:"d/m/Y"|or_empty_value_tag }}</div>
          </div>
          <div class="fr-grid-row fr-grid-row--gutters" data-testid="origin">
            <div class="fr-col-7 bold">Signalement déclaré par</div>
            <div class="fr-col-5">{{ object.get_evenement_origin_display|or_empty_value_tag }}</div>
          </div>
          <div class="fr-grid-row fr-grid-row--gutters" data-testid="modalite">
            <div class="fr-col-7 bold">Modalités de déclaration</div>
            <div class="fr-col-5">{{ object.get_modalites_declaration_display|or_empty_value_tag }}</div>
          </div>
        </div>
      </div>
      <div class="fr-col-6">
        <div class="fr-container--fluid">
          <div class="fr-grid-row fr-grid-row--gutters">
            <div class="fr-col-5 bold">Contenu du signalement</div>
            <div class="fr-col-7">{{ object.contenu|linebreaksbr }}</div>
          </div>
        </div>
      </div>
      <div class="fr-col-3">
        <div class="fr-container--fluid">
          <div class="fr-grid-row fr-grid-row--gutters">
            <div class="fr-col-5 bold">ARS informée</div>
            <div class="fr-col-7">{{ object.notify_ars|yesno:"Oui,Non,Vide" }}</div>
          </div>
          <div class="fr-grid-row fr-grid-row--gutters">
            <div class="fr-col-5 bold">Enquêtes auprès des cas</div>
            <div class="fr-col-7">{{ object.will_trigger_inquiry|yesno:"Oui,Non,Vide" }}</div>
          </div>
          <div class="fr-grid-row fr-grid-row--gutters">
            <div class="fr-col-5 bold">N° SIVSS de l'ARS</div>
            <div class="fr-col-7">{{ object.numero_sivss|or_empty_value_tag }}</div>
          </div>
          <div class="fr-grid-row fr-grid-row--gutters">
            <div class="fr-col-5 bold">Type d'événement</div>
            <div class="fr-col-7">Investigation de TIAC</div>
          </div>
          <div class="fr-grid-row fr-grid-row--gutters">
            <div class="fr-col-5 bold">Suite donnée</div>
            <div class="fr-col-7">{{ object.get_follow_up_display }}</div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

tiac/templates/tiac/_investigation_tiac_informations_agents_pathogenes.html
{% load or_empty_value_tag %}
<div class="white-container detail-content fr-mt-2w">
    <h2 class="fr-h6">Agents pathogènes confirmés par l'ARS</h2>
    {% if object.agents_confirmes_ars %}
        {{ object.agents_confirmes_ars|join:", " }}
    {% else %}
        <div class="empty-value fr-mb-2w">Vide</div>
    {% endif %}
</div>

tiac/templates/tiac/_investigation_tiac_informations_elements.html
{% load or_empty_value_tag %}
<div class="white-container detail-content fr-mt-2w">
    <h2 class="fr-h6">Éléments de l'investigation</h2>
    <div class="generic-card-container">
        {% include "tiac/_etablissements.html" %}
    </div>
    <div class="generic-card-container">
        {% include "tiac/_investigation_repas.html" %}
    </div>
    <div class="generic-card-container">
        {% include "tiac/_investigation_aliments.html" %}
    </div>
    <div class="generic-card-container">
        {% include "tiac/_investigation_analyses.html" %}
    </div>
</div>

tiac/templates/tiac/_transfer_modal.html
<dialog aria-labelledby="fr-modal-title-modal" role="dialog" id="fr-modal-transfer" class="fr-modal">
    <div class="fr-container fr-container--fluid fr-container-md">
        <div class="fr-grid-row fr-grid-row--center">
            <div class="fr-col-12 fr-col-md-10 fr-col-lg-8">
                <div class="fr-modal__body">
                    <div class="fr-modal__header">
                        <button class="fr-btn--close fr-btn" title="Fermer la fenêtre modale" aria-controls="fr-modal-transfer">Fermer</button>
                    </div>
                    <div class="fr-modal__content">
                        <h1 id="fr-modal-title-modal" class="fr-modal__title"><span class="fr-icon-arrow-right-line fr-icon--lg"></span>Transférer à une autre structure</h1>
                        <p>Veuillez choisir la structure dans la liste suivante</p>
                        <form method="post" action="{% url 'tiac:evenement-simple-transfer' evenement.pk %}">
                            <div class="fr-btns-group fr-btns-group--left fr-btns-group--inline-lg">
                                {% csrf_token %}
                                {{ transfer_form }}
                                <button type="button" class="fr-btn fr-btn--secondary" aria-controls="fr-modal-transfer">Annuler</button>
                                <button type="submit" class="fr-btn" data-testid="submit-transfer-modal">Transférer</button>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</dialog>

tiac/templates/tiac/base.html
{% extends "core/base.html" %}
{% load static waffle_tags %}

{% block base_override %}
    <link rel="stylesheet" href="{% static 'tiac/base.css' %}"/>
{% endblock %}

{% block product_nav %}
    <li class="btn-add-group fr-my-auto">
        <nav role="navigation" class="fr-translate fr-nav">
            <div class="fr-nav__item">
                <button class="fr-translate__btn fr-btn fr-btn--header-blue" aria-controls="translate-1"
                        aria-expanded="false" title="Sélectionner un type de fiche a créer">Créer un événement</button>
                <div class="fr-collapse fr-translate__menu fr-menu" id="translate-1">
                    <ul class="fr-menu__list">
                        <li><a class="fr-translate__language fr-nav__link" href="{% url 'tiac:evenement-simple-creation' %}">Enregistrement simple</a></li>
                        <li><a class="fr-translate__language fr-nav__link" href="{% url 'tiac:investigation-tiac-creation' %}">Investigation de TIAC</a></li>
                    </ul>
                </div>
            </div>
        </nav>
    </li>
    <li class="{% block highlight_menu_evenements %}{% endblock %}">
        <a class="fr-btn" href="{% url 'tiac:evenement-liste' %}">Liste des événements</a>
    </li>
{% endblock product_nav %}

tiac/templates/tiac/evenement_simple_detail.html
{% extends "tiac/base.html" %}
{% load static %}
{% load etat_tags %}
{% load or_empty_value_tag %}

{% block extrahead %}
  <link rel="stylesheet" href="{% static 'core/_etablissement_card.css' %}">
{% endblock extrahead %}
{% block scripts %}
  <script type="module" src="{% static 'core/document_form.js' %}"></script>
  <script type="module" src="{% static 'core/contact_add_form.js' %}"></script>
  <script type="module" src="{% static 'tiac/evenement_simple_details.js' %}"></script>
{% endblock %}

{% block aside %}
  {% include "core/_document_warning_modal.html" %}
{% endblock aside %}


{% block content %}
  <main class="main-container">
    <div>
      <div class="details-top-row">
        <h1 class="fr-mb-0-5v">Événement {{ object.numero }}</h1>

        {% if not object.is_draft %}
          {% include "core/_details_toogle.html" with pk=object.pk %}
        {% endif %}

        {% if can_be_deleted %}
          {% url 'tiac:evenement-liste' as next_url %}
          {% include "core/_delete_modal.html" with object=object content_type=content_type next_url=next_url%}
        {% endif %}
        {% if is_evenement_can_be_cloture %}
          {% include "core/_cloturer_modal.html" with evenement=object %}
        {% endif %}
        {% if can_be_transfered %}
          {% include "tiac/_transfer_modal.html" with evenement=object %}
        {% endif %}
        {% if can_be_changed_in_investigation %}
          {% include "tiac/_investigation_modal.html" with evenement=object %}
        {% endif %}

        <div class="details-top-row--actions">
          <ul class="fr-btns-group fr-btns-group--inline-md">
            {% if can_publish %}
              <li>
                <form action="{% url 'publish' %}" method="post">
                  {% csrf_token %}
                  <input type="hidden" value="{{ object.get_absolute_url }}" name="next">
                  <input type="hidden" value="{{ content_type.id }}" name="content_type_id">
                  <input type="hidden" value="{{ object.pk }}" name="content_id">
                  <input type="submit" class="fr-btn fr-btn--secondary" value="Publier"/>
                </form>
              </li>
            {% endif %}
            <li>
              {% include "tiac/_evenement_simple_action_navigation.html" %}
            </li>
          </ul>
        </div>

      </div>
      <p class="fr-badge fr-badge--{{etat.etat|etat_color}} fr-badge--no-icon">{{ etat.readable_etat }}</p>
    </div>

    {% include "core/_latest_revision.html" with latest_version=object.latest_version content_type_pk=content_type.pk object_pk=object.pk %}

    <div class="white-container fr-hidden synthese-content">
      {% include "tiac/_evenement_simple_informations_synthese.html" %}
    </div>

    <div class="detail-content">
      {% include "tiac/_evenement_simple_informations.html" %}
      <div class="fr-container--fluid fr-mt-2w detail-content">
        <div class="fr-grid-row fr-grid-row--gutters">
          <div class="fr-col-12">
            <div class="white-container">
              {% include "tiac/_etablissements.html" %}
            </div>
          </div>
        </div>
        {% include "core/_list_free_links.html" with classes="fr-mt-4v" title="Événements liés" object=object %}
      </div>
    </div>
    {% if not object.is_draft %}
      {% include "core/_fiche_bloc_commun.html" with object=object %}
    {% endif %}
  </main>
{% endblock content %}

tiac/templates/tiac/investigation_modification.html
{% extends "tiac/investigation.html" %}
{% load partials %}


{% block buttons %}
    {% partialdef additional_buttons inline %}
        <li>
            <a href="{% url 'tiac:evenement-liste' %}" class="fr-link">Annuler</a>
        </li>
    {% endpartialdef %}
    {{ block.super }}
{% endblock %}

{% block bottom_buttons %}
    {% partial additional_buttons %}
    {{ block.super }}
{% endblock %}