seves/urls.py
from django.conf import settings
from django.urls import include, path
from django.views.generic.base import RedirectView
from mozilla_django_oidc.urls import OIDCCallbackClass

urlpatterns = [
    path("", RedirectView.as_view(pattern_name="sv:evenement-liste"), name="index"),
    path("login-eap-callback", OIDCCallbackClass.as_view(), name="custom_oidc_authentication_callback"),
    path("sv/", include("sv.urls", namespace="sv")),
    path("ssa/", include("ssa.urls", namespace="ssa")),
    path("tiac/", include("tiac.urls", namespace="tiac")),
    path("core/", include("core.urls"), name="core"),
    path("account/", include("account.urls"), name="account"),
    path("oidc/", include("mozilla_django_oidc.urls")),
]

if settings.ADMIN_ENABLED:
    from django.contrib import admin

    admin.site.site_header = "Administration de Sèves"
    admin.site.site_title = "Sèves"
    admin.site.index_title = "Bienvenue sur l'administration de Sèves"
    urlpatterns += [
        path(f"{settings.ADMIN_URL}/", admin.site.urls),
    ]

if settings.DEBUG and settings.ENVIRONMENT != "test":
    urlpatterns.append(path("__debug__/", include("debug_toolbar.urls")))

sv/urls.py
from django.urls import path

from .api_views import search_espece_echantillon
from .views import (
    EvenementDetailView,
    EvenementListView,
    EvenementUpdateView,
    EvenementVisibiliteUpdateView,
    FicheDetectionCreateView,
    FicheDetectionExportView,
    FicheDetectionUpdateView,
    FicheZoneDelimiteeCreateView,
    FicheZoneDelimiteeDeleteView,
    FicheZoneDelimiteeUpdateView,
    VisibiliteStructureView,
)

app_name = "sv"
urlpatterns = [
    path(
        "evenements/",
        EvenementListView.as_view(),
        name="evenement-liste",
    ),
    path(
        "evenement/<str:numero>/",
        EvenementDetailView.as_view(),
        name="evenement-details",
    ),
    path(
        "evenement/<int:pk>/modification/",
        EvenementUpdateView.as_view(),
        name="evenement-update",
    ),
    path(
        "fiches-detection/creation/",
        FicheDetectionCreateView.as_view(),
        name="fiche-detection-creation",
    ),
    path(
        "fiches-detection/export/",
        FicheDetectionExportView.as_view(),
        name="fiche-detection-export",
    ),
    path(
        "fiches-detection/<int:pk>/modification/",
        FicheDetectionUpdateView.as_view(),
        name="fiche-detection-modification",
    ),
    path(
        "evenement/<int:pk>/visibilite/",
        EvenementVisibiliteUpdateView.as_view(),
        name="evenement-visibilite-update",
    ),
    path(
        "api/espece/recherche/",
        search_espece_echantillon,
        name="api-search-espece",
    ),
    path(
        "fiche-zone-delimitee/creation/",
        FicheZoneDelimiteeCreateView.as_view(),
        name="fiche-zone-delimitee-creation",
    ),
    path(
        "fiche-zone-delimitee/<int:pk>/modification/",
        FicheZoneDelimiteeUpdateView.as_view(),
        name="fiche-zone-delimitee-update",
    ),
    path(
        "evenement/<int:pk>/structures/ajout/visibilite",
        VisibiliteStructureView.as_view(),
        name="structure-add-visibilite",
    ),
    path(
        "fiche-zone-delimitee/<int:pk>/delete/",
        FicheZoneDelimiteeDeleteView.as_view(),
        name="fiche-zone-delimitee-delete",
    ),
]

sv/models/common.py
from django.db import models


class OrganismeNuisible(models.Model):
    class Meta:
        verbose_name = "Organisme nuisible"
        verbose_name_plural = "Organismes nuisibles"
        db_table = "sv_organisme_nuisible"
        constraints = [
            models.UniqueConstraint(
                fields=["code_oepp", "libelle_court"], name="unique_organisme_nuisible_code_libelle"
            )
        ]

    code_oepp = models.CharField(verbose_name="Code OEPP", unique=True)
    libelle_court = models.CharField(max_length=255, verbose_name="Nom", unique=True)
    libelle_long = models.CharField(max_length=255, verbose_name="Nom", unique=True)

    def __str__(self):
        return self.libelle_court


class StatutReglementaire(models.Model):
    class Meta:
        verbose_name = "Statut règlementaire de l'organisme"
        verbose_name_plural = "Statuts règlementaires de l'organisme"
        db_table = "sv_statut_reglementaire"
        constraints = [
            models.UniqueConstraint(fields=["code", "libelle"], name="unique_statut_reglementaire_code_libelle")
        ]

    code = models.CharField(max_length=10, verbose_name="Code", unique=True)
    libelle = models.CharField(max_length=100, verbose_name="Libellé", unique=True)

    def __str__(self):
        return self.libelle


class Etat(models.Model):
    NOUVEAU = "nouveau"
    EN_COURS = "en cours"
    CLOTURE = "clôturé"

    class Meta:
        verbose_name = "Etat"
        verbose_name_plural = "Etats"
        db_table = "sv_etat"

    libelle = models.CharField(max_length=30, unique=True)

    @classmethod
    def get_etat_initial(cls):
        return cls.objects.get(libelle=cls.NOUVEAU).id


class StatutEtablissement(models.Model):
    class Meta:
        verbose_name = "Statut de l'établissement"
        verbose_name_plural = "Statuts de l'établissement"
        db_table = "sv_statut_etablissement"

    libelle = models.CharField(max_length=100, verbose_name="Libellé", unique=True)

    def __str__(self):
        return self.libelle

sv/models/lieux.py
from django.core.exceptions import ValidationError
from django.core.validators import RegexValidator
from django.db import models, transaction
from django_countries.fields import CountryField
import reversion

from core.models import Departement, Region  # noqa F403


class PositionChaineDistribution(models.Model):
    class Meta:
        verbose_name = "Position dans la chaîne de distribution"
        verbose_name_plural = "Positions dans la chaîne de distribution"
        db_table = "sv_position_chaine_distribution"

    libelle = models.CharField(max_length=100, verbose_name="Libellé", unique=True)

    def __str__(self):
        return self.libelle


class SiteInspection(models.Model):
    class Meta:
        verbose_name = "Site d'inspection"
        verbose_name_plural = "Sites d'inspection"
        db_table = "sv_site_inspection"

    nom = models.CharField(max_length=100, verbose_name="Nom", unique=True)

    def __str__(self):
        return self.nom


def validate_wgs84_longitude(value):
    if value is not None and (value < -180 or value > 180):
        raise ValidationError("La longitude doit être comprise entre -180° et +180°")


def validate_wgs84_latitude(value):
    if value is not None and (value < -90 or value > 90):
        raise ValidationError("La latitude doit être comprise entre -90° et +90°")


@reversion.register()
class Lieu(models.Model):
    class Meta:
        verbose_name = "Lieu"
        verbose_name_plural = "Lieux"

    fiche_detection = models.ForeignKey(
        "FicheDetection",
        on_delete=models.CASCADE,
        verbose_name="Fiche de détection",
        related_name="lieux",
    )
    nom = models.CharField(max_length=100, verbose_name="Nom")
    wgs84_longitude = models.FloatField(
        verbose_name="Longitude WGS84", blank=True, null=True, validators=[validate_wgs84_longitude]
    )
    wgs84_latitude = models.FloatField(
        verbose_name="Latitude WGS84", blank=True, null=True, validators=[validate_wgs84_latitude]
    )
    adresse_lieu_dit = models.CharField(max_length=100, verbose_name="Adresse ou lieu-dit", blank=True)
    commune = models.CharField(max_length=100, verbose_name="Commune", blank=True)
    code_insee = models.CharField(
        max_length=5,
        blank=True,
        verbose_name="Code INSEE de la commune",
        validators=[
            RegexValidator(
                regex=r"^(?:\d{5}|2A\d{3}|2B\d{3})$",
                message="Le code INSEE doit être valide",
                code="invalid_code_insee",
            ),
        ],
    )
    departement = models.ForeignKey(
        Departement,
        on_delete=models.PROTECT,
        verbose_name="Département",
        blank=True,
        null=True,
    )
    is_etablissement = models.BooleanField(verbose_name="Établissement", default=False)
    activite_etablissement = models.CharField(max_length=100, verbose_name="Activité établissement", blank=True)
    pays_etablissement = CountryField(verbose_name="Pays établissement", blank=True)
    raison_sociale_etablissement = models.CharField(
        max_length=100, verbose_name="Raison sociale établissement", blank=True
    )
    adresse_etablissement = models.CharField(max_length=100, verbose_name="Adresse établissement", blank=True)
    commune_etablissement = models.CharField(max_length=100, verbose_name="Commune", blank=True)
    code_insee_etablissement = models.CharField(
        max_length=5,
        blank=True,
        verbose_name="Code INSEE de la commune",
        validators=[
            RegexValidator(
                regex="^[0-9]{5}$",
                message="Le code INSEE doit contenir exactement 5 chiffres",
                code="invalid_code_insee",
            ),
        ],
    )
    departement_etablissement = models.ForeignKey(
        Departement,
        on_delete=models.PROTECT,
        verbose_name="Département",
        blank=True,
        null=True,
        related_name="departement_etablissement",
    )
    siret_etablissement = models.CharField(
        max_length=14,
        verbose_name="SIRET établissement",
        blank=True,
        validators=[
            RegexValidator(
                regex="^[0-9]{14}$",
                message="Le SIRET doit contenir exactement 14 chiffres",
                code="invalid_siret",
            ),
        ],
    )
    site_inspection = models.ForeignKey(
        "SiteInspection",
        on_delete=models.PROTECT,
        verbose_name="Site d'inspection",
        blank=True,
        null=True,
    )
    position_chaine_distribution_etablissement = models.ForeignKey(
        "PositionChaineDistribution",
        on_delete=models.PROTECT,
        verbose_name="Position dans la chaîne de distribution établissement",
        blank=True,
        null=True,
    )
    code_inupp_etablissement = models.CharField(max_length=10, verbose_name="Code INUPP", blank=True)

    ETABLISSEMENT_FIELDS = [
        "activite_etablissement",
        "pays_etablissement",
        "raison_sociale_etablissement",
        "adresse_etablissement",
        "siret_etablissement",
        "code_inupp_etablissement",
        "position_chaine_distribution_etablissement",
    ]

    def __str__(self):
        return str(self.nom)

    def save(self, *args, **kwargs):
        from sv.models import FicheDetection

        with transaction.atomic():
            with reversion.create_revision():
                super().save(*args, **kwargs)
            FicheDetection.objects.update_date_derniere_mise_a_jour(self.fiche_detection.id)

sv/models/models_mixins.py
from django.db import models


class WithDerniereMiseAJourMixin(models.Model):
    date_derniere_mise_a_jour = models.DateTimeField(
        db_index=True,
        null=True,
        blank=True,
        auto_now=True,
        verbose_name="Date dernière mise à jour",
    )

    class Meta:
        abstract = True

sv/models/prelevements.py
import re

from django.core.exceptions import ValidationError
from django.db import models
from django.db.models import Q
import reversion

from core.mixins import IsActiveMixin
from sv.constants import STRUCTURE_EXPLOITANT
from sv.managers import (
    LaboratoireManager,
    StructurePreleveuseManager,
)

from .lieux import Lieu


class MatricePrelevee(models.Model):
    class Meta:
        verbose_name = "Matrice prélevée"
        verbose_name_plural = "Matrices prélevées"
        db_table = "sv_matrice_prelevee"

    libelle = models.CharField(max_length=100, verbose_name="Libellé", unique=True)

    def __str__(self):
        return self.libelle


class StructurePreleveuse(IsActiveMixin, models.Model):
    class Meta:
        verbose_name = "Structure préleveuse"
        verbose_name_plural = "Structures préleveuses"
        db_table = "sv_structure_preleveur"
        ordering = ["nom"]

    nom = models.CharField(max_length=100, verbose_name="Nom", unique=True)

    objects = StructurePreleveuseManager()

    def __str__(self):
        return self.nom


class EspeceEchantillon(models.Model):
    class Meta:
        verbose_name = "Espèce de l'échantillon"
        verbose_name_plural = "Espèces de l'échantillon"
        db_table = "sv_espece_echantillon"
        constraints = [
            models.UniqueConstraint(fields=["code_oepp", "libelle"], name="unique_espece_echantillon_codeoepp_libelle")
        ]

    code_oepp = models.CharField(max_length=100, verbose_name="Code OEPP", unique=True)
    libelle = models.CharField(max_length=100, verbose_name="Libellé", unique=True)

    def __str__(self):
        return self.libelle


class Laboratoire(IsActiveMixin, models.Model):
    class Meta:
        verbose_name = "Laboratoire"
        verbose_name_plural = "Laboratoires"
        ordering = ["nom"]

    nom = models.CharField(max_length=100, verbose_name="Nom", unique=True)
    confirmation_officielle = models.BooleanField(
        default=False, verbose_name="Peut fournir une confirmation officielle"
    )

    def __str__(self):
        return self.nom

    objects = LaboratoireManager()


def validate_numero_rapport_inspection(value):
    pattern = r"^\d{2}-\d{6}$"
    if not re.match(pattern, value):
        raise ValidationError(
            "Le format doit être AA-XXXXXX où AA correspond à l'année sur 2 chiffres (ex: 24 pour 2024) et XXXXXX est un numéro à 6 chiffres"
        )


@reversion.register()
class Prelevement(models.Model):
    class Resultat(models.TextChoices):
        DETECTE = "detecte", "Détecté"
        NON_DETECTE = "non_detecte", "Non détecté"
        NON_CONCLUSIF = "non_conclusif", "Non conclusif"
        EN_ATTENTE = "en_attente", "En attente"

    class TypeAnalyse(models.TextChoices):
        PREMIERE_INTENTION = "premiere_intention", "1ère intention"
        CONFIRMATION = "confirmation", "Confirmation"

    class Meta:
        verbose_name = "Prélèvement"
        verbose_name_plural = "Prélèvements"
        db_table = "sv_prelevement"
        constraints = [
            models.CheckConstraint(
                condition=Q(is_officiel=True) | Q(numero_rapport_inspection=""),
                name="check_numero_officiel_empty_or_null",
            )
        ]

    lieu = models.ForeignKey(Lieu, on_delete=models.CASCADE, verbose_name="Lieu", related_name="prelevements")
    structure_preleveuse = models.ForeignKey(
        StructurePreleveuse, on_delete=models.PROTECT, verbose_name="Structure préleveuse"
    )
    numero_echantillon = models.CharField(max_length=100, verbose_name="N° d'échantillon", blank=True)
    date_prelevement = models.DateField(verbose_name="Date de prélèvement", blank=True, null=True)
    matrice_prelevee = models.ForeignKey(
        MatricePrelevee,
        on_delete=models.PROTECT,
        verbose_name="Nature de l'objet",
        blank=True,
        null=True,
    )
    espece_echantillon = models.ForeignKey(
        EspeceEchantillon,
        on_delete=models.PROTECT,
        verbose_name="Espèce de l'échantillon",
        blank=True,
        null=True,
    )
    is_officiel = models.BooleanField(verbose_name="Prélèvement officiel", default=False)
    laboratoire = models.ForeignKey(
        "Laboratoire",
        on_delete=models.PROTECT,
        verbose_name="Laboratoire",
        blank=True,
        null=True,
    )
    resultat = models.CharField(max_length=50, choices=Resultat.choices, verbose_name="Résultat")
    type_analyse = models.CharField(
        max_length=50,
        choices=TypeAnalyse.choices,
        verbose_name="Type d'analyse",
        default=TypeAnalyse.PREMIERE_INTENTION,
    )
    numero_rapport_inspection = models.CharField(
        max_length=9,
        verbose_name="Numéro du rapport d'inspection",
        blank=True,
        validators=[validate_numero_rapport_inspection],
    )
    date_rapport_analyse = models.DateField(verbose_name="Date rapport d'analyse", blank=True, null=True)

    def __str__(self):
        return f"Prélèvement n° {self.id}"

    def clean(self):
        super().clean()
        if self.is_officiel and self.structure_preleveuse.nom == STRUCTURE_EXPLOITANT:
            raise ValidationError("Le prélèvement ne peut pas être officiel pour une structure 'Exploitant'")

        if (
            self.type_analyse == self.TypeAnalyse.CONFIRMATION
            and self.laboratoire
            and self.laboratoire.confirmation_officielle is False
        ):
            raise ValidationError(
                "Un prélèvement de confirmation ne peut être réalisé que par un laboratoire de confirmation officielle"
            )

    def save(self, *args, **kwargs):
        self.clean()
        with reversion.create_revision():
            super().save(*args, **kwargs)

sv/templates/sv/_evenement_badges.html
{% load etat_tags %}

<div>
    {% if evenement.is_ac_notified %}
        <p class="fr-badge ac-notified"><span class="fr-icon-notification-3-line fr-mr-2v fr-icon--sm" aria-hidden="true"></span> Déclaré AC</p>
    {% endif %}
    <p class="fr-badge fr-badge--no-icon">{{ evenement.visibility_display }}</p>
    <p class="fr-badge fr-badge--{{etat.etat|etat_color}} fr-badge--no-icon">{{ etat.readable_etat }}</p>
</div>

sv/templates/sv/evenement_detail.html
{% extends 'sv/base.html' %}

{% load static %}
{% load etat_tags %}

{% block extrahead %}
    <link rel="stylesheet" href="{% static 'sv/common.css' %}">
    <link rel="stylesheet" href="{% static 'sv/evenement_details.css' %}">
    <link rel="stylesheet" href="{% static 'core/has_sidebar.css' %}">
    <link rel="stylesheet" href="{% static 'sv/fichedetection_detail.css' %}">
    <link rel="stylesheet" href="{% static 'sv/fichezonedelimitee_detail.css' %}">
{% endblock %}

{% block scripts %}
    <script type="module" src="{% static 'sv/evenement_details.js' %}"></script>
    <script type="module" src="{% static 'core/document_form.js' %}"></script>
    <script type="module" src="{% static 'core/contact_add_form.js' %}"></script>
{% endblock %}

{% block aside %}
    {% include "core/_document_warning_modal.html" %}
{% endblock aside %}

{% block content %}
    <main class="main-container">
        <div data-testid="evenement-header">
            <div class="details-top-row">
                <h1 class="fr-mb-0-5v">Événement {% if evenement.numero %}{{ evenement.numero }}{%  endif %}</h1>

                {% if not evenement.is_draft %}
                    {% include "core/_details_toogle.html" with pk=evenement.pk %}
                {% endif %}

                <ul class="fr-btns-group fr-btns-group--inline-md">
                    {% if can_publish %}
                        <li>
                            {% if request.user.agent.structure.is_ac %}
                                <form action="{% url 'publish' %}" method="post">
                                    {% csrf_token %}
                                    <input type="hidden" value="{{ evenement.get_absolute_url }}" name="next">
                                    <input type="hidden" value="{{ content_type.id }}" name="content_type_id">
                                    <input type="hidden" value="{{ evenement.pk }}" name="content_id">
                                    <input type="submit" class="fr-btn fr-btn--secondary" value="Publier"/>
                                </form>
                            {% else %}
                                <button class="fr-btn fr-btn--secondary fr-mr-1w" data-fr-opened="false" aria-controls="fr-modal-publier-without-notifier-ac">Publier sans déclarer à l'AC</button>
                            {% endif %}
                        </li>
                        {% if not request.user.agent.structure.is_ac %}
                            <li>
                                <button class="fr-btn fr-btn--secondary" data-fr-opened="false" aria-controls="fr-modal-publier-and-notifier-ac">Publier et déclarer à l'AC</button>
                            </li>
                        {% endif %}
                    {% endif %}
                    <li>
                        <div class="details-top-row--actions">{% include "sv/_evenement_action_navigation.html" %}</div>
                    </li>
                </ul>
                {% if can_ouvrir %}
                    <button class="fr-btn" data-fr-opened="false" aria-controls="fr-annuler-cloture-modal">Ouvrir l'évènement</button>
                    {% include "core/_ouvrir_evenement_modal.html" %}
                {% endif %}
                {% if can_be_ac_notified %}
                    {% include "core/_notifier_ac_modale.html" with object=evenement %}
                {% endif %}

                {% if can_update_visibilite %}
                    {% include "sv/_update_visibilite_modale.html" %}
                {% endif %}
                {% if is_evenement_can_be_cloture %}
                    {% include "core/_cloturer_modal.html" %}
                {% endif %}
                {% if can_be_deleted %}
                    {% url 'sv:evenement-liste' as next_url %}
                    {% include "core/_delete_modal.html" with object=evenement content_type=content_type next_url=next_url%}
                {% endif %}
            </div>
            {% include "sv/_evenement_badges.html" %}
            {% include "sv/_latest_revision.html" with content_type_pk=content_type.pk object_pk=evenement.pk %}
        </div>

        <div class="fr-container--fluid fr-mb-4v">
            <div class="fr-grid-row white-container--lite">
                <div class="fr-col-12 fr-col-lg-4">
                    <div class="fr-mb-2v"><span class="bold fr-mr-2v">Organisme nuisible</span> {{ evenement.organisme_nuisible }}</div>
                    <div class="fr-mb-2v"><span class="bold fr-mr-2v">Statut réglementaire</span> {{ evenement.statut_reglementaire }}</div>
                    <div class="fr-mb-2v"><span class="bold fr-mr-2v">Code OEPP</span> {{ evenement.organisme_nuisible.code_oepp }}</div>
                </div>
                <div class="fr-col-12 fr-col-lg-3">
                    <div class="fr-mb-2v"><span class="bold fr-mr-2v">Date de création</span> {{ evenement.date_creation|date }}</div>
                    <div class="fr-mb-2v"><span class="bold fr-mr-2v">Créateur</span> {{ evenement.createur }}</div>
                </div>
                <div class="fr-col-12 fr-col-lg-5">
                    <div class="fr-mb-2v">
                        <span class="bold fr-mr-2v">Visibilité</span>
                        <span data-testid="evenement-visibilite">
                            {% with structures_str=evenement.get_visibilite_display_text %}
                                {% if evenement.is_visibilite_limitee and structures_str|length > 150 %}
                                    {{ structures_str|truncatechars:150 }}
                                    <button class="fr-btn--tooltip fr-btn" aria-describedby="tooltip-visibilite" type="button"></button>
                                    <span class="fr-tooltip fr-placement" id="tooltip-visibilite" role="tooltip" aria-hidden="true">{{ structures_str }}</span>
                                {% else %}
                                    {{ structures_str }}
                                {% endif %}
                            {% endwith %}
                        </span>
                    </div>
                    <div class="fr-mb-2v"><span class="bold fr-mr-2v">N° Europhyt</span> {{ evenement.numero_europhyt }}</div>
                    <div class="fr-mb-2v"><span class="bold fr-mr-2v">N° RASFF</span> {{ evenement.numero_rasff }}</div>
                </div>

            </div>
        </div>

        {% include "core/_list_free_links.html" with classes="fr-mb-4v" object=evenement title="Événements liés" %}

        <div class="detail-content">
            <div class="fr-tabs">
                <ul class="fr-tabs__list" role="tablist" aria-label="Navigation entre zone et détections">
                    <li role="presentation">
                        <button id="tabpanel-detection" class="fr-tabs__tab" tabindex="0" role="tab" aria-selected="false"  aria-controls="tabpanel-detection-panel">Détections</button>
                    </li>
                    <li role="presentation">
                        <button id="tabpanel-zone" class="fr-tabs__tab" tabindex="-1" role="tab" aria-selected="false" aria-controls="tabpanel-zone-panel">Zone</button>
                    </li>
                </ul>
                <div id="tabpanel-detection-panel" class="fr-tabs__panel fr-tabs__panel--selected" role="tabpanel" aria-labelledby="tabpanel-detection" tabindex="0">
                    <div>
                        <div class="fr-tabs no-tab-look">
                            <ul class="fr-tabs__list" role="tablist" aria-label="Liste des détections">
                                {% for fichedetection in evenement.detections.all %}
                                    <li role="presentation">
                                        <button id="tabpanel-{{ fichedetection.pk }}"
                                                class="fr-tag fr-mx-1w {% if fichedetection.pk == active_detection %}selected{% endif %}"
                                                tabindex="{% if fichedetection.pk == active_detection %}0{% else %}-1{% endif %}"
                                                role="tab"
                                                aria-selected="{% if fichedetection.pk == active_detection %}true{% else %}false{% endif %}"
                                                aria-controls="tabpanel-{{ fichedetection.pk }}-panel">{{ fichedetection }}</button>
                                    </li>
                                {% endfor %}
                                {% if can_add_fiche_detection %}
                                    <li>
                                        <a id="add-detection-link" href="{% url 'sv:fiche-detection-creation' %}?evenement={{ evenement.pk }}" class="fr-tag fr-tag--tertiary fr-mx-1w">
                                            <span class="fr-icon-add-line" aria-hidden="true"></span> Ajouter une détection</a>
                                    </li>
                                {% endif %}
                            </ul>

                            {% for fichedetection in evenement.detections.all %}
                                <div id="detection-actions-{{ fichedetection.pk }}" {% if not fichedetection.pk == active_detection %}class="fr-hidden"{% endif %}>
                                    {% if can_delete_fiche_detection %}
                                        <button class="fr-btn fr-btn--delete fr-mr-2w" data-fr-opened="false" aria-controls="fr-modal-delete-detection-{{ fichedetection.pk }}">
                                            Supprimer la détection
                                        </button>
                                        {% include "sv/_delete_fiche_modal.html" with prefix="detection" content_type=fiche_detection_content_type object_pk=fichedetection.pk %}
                                    {% endif %}
                                    {% if can_update_fiche_detection %}
                                        <button class="fr-btn fr-btn--secondary">
                                            <a href="{% url 'sv:fiche-detection-modification' fichedetection.pk %}">Modifier la détection</a>
                                        </button>
                                    {% endif %}
                                </div>
                            {% endfor %}


                            {% for fichedetection in evenement.detections.all %}
                                <div id="tabpanel-{{ fichedetection.pk }}-panel"
                                     class="fr-tabs__panel {% if fichedetection.pk == active_detection %}fr-tabs__panel--selected{% endif %}"
                                     role="tabpanel"
                                     aria-labelledby="tabpanel-{{ fichedetection.pk }}"
                                     tabindex="{% if fichedetection.pk == active_detection %}0{% else %}-1{% endif %}">
                                    {% include "sv/_fichedetection_detail.html" %}
                                </div>
                            {% endfor %}
                        </div>
                    </div>
                </div>
                <div id="tabpanel-zone-panel" class="fr-tabs__panel" role="tabpanel" aria-labelledby="tabpanel-zone" tabindex="0">
                    {% if evenement.fiche_zone_delimitee %}
                        {% include "sv/fichezonedelimitee_detail.html" with fiche=evenement.fiche_zone_delimitee %}
                    {% else %}
                        <div class="white-container fr-pb-6w">
                            <h3>Cet événement ne contient pas de zone</h3>
                            {% if can_add_fiche_zone_delimitee %}
                                <a href="{% url 'sv:fiche-zone-delimitee-creation' %}?evenement={{ evenement.pk }}" class="zone-button "><button class="fr-btn fr-btn--secondary fr-mr-2w fr-btn--icon-left fr-icon-add-line">Ajouter une zone</button></a>
                            {% endif %}
                        </div>
                    {% endif %}
                </div>
            </div>
        </div>

        {% if not evenement.is_draft %}
            {% include "core/_fiche_bloc_commun.html" with object=evenement %}
        {% endif %}

    </main>

    {% if can_publish %}
        {% include "core/_publier_without_notifier_ac_modal.html" %}
        {% include "core/_publier_and_notifier_ac_modal.html" %}
    {% endif %}

{% endblock %}